import cv2 as cv
from matplotlib import pyplot as pt
img = cv.imread('gradient.jpeg.jpg',0)
ret,thresh1 = cv.threshold(img,127,255,cv.THRESH_BINARY)
ret,thresh2 = cv.threshold(img,127,255,cv.THRESH_BINARY_INV)
ret,thresh3 = cv.threshold(img,127,255,cv.THRESH_TRUNC)
ret,thresh4 = cv.threshold(img,127,255,cv.THRESH_TOZERO)
ret,thresh5 = cv.threshold(img,127,255,cv.THRESH_TOZERO_INV)
cv.imshow('OG',img)
cv.imshow('THRESH1',thresh1)
cv.imshow('THRESH2',thresh2)
cv.imshow('THRESH3',thresh3)
cv.imshow('THRESH4',thresh4)
cv.imshow('THRESH5',thresh5)
cv.waitKey(0)
cv.destroyAllWindows()
